# Generated by Django 3.0.2 on 2020-01-12 06:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('nconst', models.CharField(max_length=20)),
                ('primaryName', models.CharField(max_length=30)),
                ('birthYear', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('deathYear', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('primaryProfession', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=3)),
            ],
            options={
                'db_table': 'tbl_actor',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('titleId', models.AutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=20)),
                ('titleType', models.CharField(max_length=20)),
                ('primaryTitle', models.CharField(max_length=100)),
                ('originalTitle', models.CharField(max_length=100)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('endYear', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('runtimeMinutes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The runtime of title must be at least 1')])),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=3)),
            ],
            options={
                'db_table': 'tbl_title',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('titleId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='titles.Title')),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='The number of votes must be at least 0')])),
            ],
            options={
                'db_table': 'tbl_rating',
            },
        ),
        migrations.CreateModel(
            name='TitleActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Actor')),
                ('titleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
            options={
                'db_table': 'tbl_title_actor',
            },
        ),
    ]
