# Generated by Django 3.0.2 on 2020-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20200112_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='primary_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.CharField(max_length=450),
        ),
    ]
