# Generated by Django 3.0.2 on 2020-01-13 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20200112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='primary_profession',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), null=True, size=3),
        ),
    ]
