# Generated by Django 3.0.2 on 2020-01-14 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20200112_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='title_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='titles.Title'),
        ),
    ]
