# Generated by Django 3.0.2 on 2020-01-14 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20200113_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleactor',
            name='actor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='titles.Actor'),
        ),
        migrations.AlterField(
            model_name='titleactor',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='titles.Title'),
        ),
    ]
