# Generated by Django 3.0.2 on 2020-01-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20200113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
