# Generated by Django 3.0.2 on 2020-01-10 22:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('nconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(max_length=30)),
                ('birthYear', models.CharField(max_length=4)),
                ('deathYear', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=15)),
                ('primaryTitle', models.CharField(max_length=100)),
                ('originalTitle', models.CharField(max_length=100)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('endYear', models.IntegerField(default=django.db.models.deletion.SET_NULL, validators=[django.core.validators.MinValueValidator(1, message='The year must be at least 1'), django.core.validators.MaxValueValidator(9999, message='The year must be up to 9999')])),
                ('runtimeMinutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='The runtime of title must be at least 1')])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='The number of votes must be at least 0')])),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor')),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
